### ISSUE TITLE
Failed to build Docker Image for athenz-cli-util.

### ISSUE THREAD

**Issue by hiyosi** [yahoo/athenz#870]
Hi, I tried the latest master branch to build Athenz Docker Images.
But it didn't work.

```
$ git rev-parse --short HEAD
4e7863d8

$ cd `git rev-parse --show-toplevel`/docker

$ make build | tee ./athenz-docker-build.log
```

Since `athenz-cert-refresher` not found, mvn install failed for `athenz-zts-java-client-core`.

```
[INFO] ------------< com.yahoo.athenz:athenz-zts-java-client-core >------------
[INFO] Building athenz-zts-java-client-core 1.8.45-SNAPSHOT              [6/23]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.yahoo.athenz:athenz-cert-refresher:jar:1.8.45-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for rdl-gen-athenz-go-client 1.8.45-SNAPSHOT:
[INFO]
[INFO] rdl-gen-athenz-go-client ........................... SUCCESS [ 31.582 s]
[INFO] athenz-zms-core .................................... SUCCESS [ 16.657 s]
[INFO] athenz-zts-core .................................... SUCCESS [  6.829 s]
[INFO] athenz-auth-core ................................... SUCCESS [  8.331 s]
[INFO] athenz-client-common ............................... SUCCESS [  0.518 s]
[INFO] athenz-zts-java-client-core ........................ FAILURE [  0.114 s]
[INFO] athenz-zts-java-client ............................. SKIPPED
[INFO] zms-go-client ...................................... SKIPPED
[INFO] zts-go-client ...................................... SKIPPED
[INFO] zmscli ............................................. SKIPPED
[INFO] zmssvctoken ........................................ SKIPPED
[INFO] ztsclientutil ...................................... SKIPPED
[INFO] athenzconf ......................................... SKIPPED
[INFO] zms-cli ............................................ SKIPPED
[INFO] athenz-conf ........................................ SKIPPED
[INFO] zms-svctoken ....................................... SKIPPED
[INFO] athenz-zpe-policy-updater .......................... SKIPPED
[INFO] zpe-updater ........................................ SKIPPED
[INFO] zts-roletoken ...................................... SKIPPED
[INFO] zts-accesstoken .................................... SKIPPED
[INFO] zts-rolecert ....................................... SKIPPED
[INFO] zts-svccert ........................................ SKIPPED
[INFO] athenz-utils ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:04 min
[INFO] Finished at: 2020-01-29T06:22:44Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project athenz-zts-java-client-core: Could not resolve dependencies for project com.yahoo.athenz:athenz-zts-java-client-core:jar:1.8.45-SNAPSHOT: Could not find artifact com.yahoo.athenz:athenz-cert-refresher:jar:1.8.45-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :athenz-zts-java-client-core
The command '/bin/sh -c GO111MODULE=on   CGO_ENABLED=0   CGO_CXXFLAGS="-g -Ofast -march=native"   CGO_FFLAGS="-g -Ofast -march=native"   CGO_LDFLAGS="-g -Ofast -march=native"   GOOS=$(go env GOOS)   GOARCH=$(go env GOARCH)   mvn install -Dmaven.test.skip=true   -pl core/zms   -pl core/zts   -pl libs/java/auth_core   -pl libs/java/client_common   -pl clients/java/zts/core   -pl clients/java/zts/shade   -pl rdl/rdl-gen-athenz-go-client   -pl clients/go/zms   -pl clients/go/zts   -pl libs/go/zmscli   -pl libs/go/zmssvctoken   -pl libs/go/athenzutils   -pl libs/go/athenzconf   -pl utils/zms-cli   -pl utils/athenz-conf   -pl utils/zms-svctoken   -pl utils/zpe_policy_updater   -pl utils/zpe-updater   -pl utils/zts-roletoken   -pl utils/zts-accesstoken   -pl utils/zts-rolecert   -pl utils/zts-svccert   -pl assembly/utils' returned a non-zero code: 1
make: *** [build] Error 1
```

In my environment, I could resolve the above error with below fixes. ( I can send a PR)

```diff
diff --git a/docker/util/Dockerfile b/docker/util/Dockerfile
index 3ef90ef6..031f86bd 100644
--- a/docker/util/Dockerfile
+++ b/docker/util/Dockerfile
@@ -23,6 +23,7 @@ RUN GO111MODULE=on \
   -pl core/zts \
   -pl libs/java/auth_core \
   -pl libs/java/client_common \
+  -pl libs/java/cert_refresher \
   -pl clients/java/zts/core \
   -pl clients/java/zts/shade \
   # go projects
```

**Comment by WindzCUHK** [comment]
@hiyosi Thank you for reporting this. It is caused by a recent update on the dependency.

I am working on the new Athenz bootstrap that does not require the `athenz-cli-util` docker image during the setup process.
https://github.com/WindzCUHK/athenz/blob/zms-on-external-IdP/docker/Makefile
It is still WIP, but it works on the latest `1.8.45`.

**Comment by hiyosi** [comment]
@WindzCUHK 
Thanks for reply!

I've tried your working branch once 😀
The Docker image was created successfully, but the dev environment setup failed.

```
...
Will start ZMS server...
9b6bb885db45705a5bc774fa0e12e1cdfe2d6029fa7e455182df808592f0b613

Will wait for ZMS to be ready...
ZMS is unavailable - will sleep 3s...
ZMS is up!
Debug ZMS
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
        at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:594)
        ... 42 common frames omitted
03:14:25.906 [main] INFO  o.e.j.util.ssl.SslContextFactory - x509=X509@119cbf96(1,h=[localhost, not defined],w=[]) for Server@5454d35e[provider=null,keyStore=file:///opt/athenz/zms/var/certs/zms_keystore.pkcs12,trustStore=file:///opt/athenz/zms/var/certs/zms_truststore.jks]
03:14:25.939 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@3712b94{SSL,[ssl, http/1.1]}{0.0.0.0:4443}
03:14:25.939 [main] INFO  org.eclipse.jetty.server.Server - Started @1288ms
add ZMS host
127.0.0.1 athenz-zms-server
/etc/hosts already set
ZMS health check
make: *** [deploy-dev] Error 60
```
```
$ cat logs/zms/server.log

03:14:24.981 [main] INFO  c.y.a.c.s.util.ConfigProperties - Loading system properties from conf/zms_server/athenz.properties...
03:14:24.983 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.ssl_key_store, value=/opt/athenz/zms/var/certs/zms_keystore.pkcs12
03:14:24.983 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.ssl_trust_store_type, value=JKS
03:14:24.983 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.port, value=0
03:14:24.984 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.tls_port, value=4443
03:14:24.984 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.access_log_dir, value=/opt/athenz/zms/logs/zms_server
03:14:24.984 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.ssl_key_store_type, value=PKCS12
03:14:24.984 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.ssl_trust_store, value=/opt/athenz/zms/var/certs/zms_truststore.jks
03:14:24.985 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.jetty_home, value=/opt/athenz/zms
03:14:24.998 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @344ms to org.eclipse.jetty.util.log.Slf4jLog
03:14:25.076 [main] INFO  c.y.a.c.AthenzJettyContainer - Using SSL KeyStore path: /opt/athenz/zms/var/certs/zms_keystore.pkcs12
03:14:25.087 [main] INFO  c.y.a.c.AthenzJettyContainer - Using SSL TrustStore path: /opt/athenz/zms/var/certs/zms_truststore.jks
03:14:25.142 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_242-b08
03:14:25.173 [main] INFO  org.eclipse.jetty.server.session - DefaultSessionIdManager workerName=node0
03:14:25.174 [main] INFO  org.eclipse.jetty.server.session - No SessionScavenger set, using defaults
03:14:25.175 [main] INFO  org.eclipse.jetty.server.session - node0 Scavenging every 660000ms
03:14:25.182 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@18bf3d14{/,null,AVAILABLE}
03:14:25.187 [main] INFO  o.e.jetty.server.RequestLogWriter - Opened /opt/athenz/zms/logs/zms_server/access.2020_02_05.log
03:14:25.188 [main] INFO  o.e.j.d.p.ScanningAppProvider - Deployment monitor [file:///opt/athenz/zms/webapps/] at interval 60
03:14:25.609 [main] DEBUG c.y.a.c.filter.RateLimitFilter - Registered rate limit filter: com.yahoo.athenz.common.filter.impl.NoOpRateLimitFactory
03:14:25.836 [main] INFO  c.y.a.c.s.util.ConfigProperties - Loading system properties from conf/zms_server/zms.properties...
03:14:25.837 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.auth.oauth.jwt.claim.iss, value=https://wzdev.auth0.com/
03:14:25.837 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.zms.read_only_mode, value=false
03:14:25.837 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.auth.private_key_store.private_key, value=/opt/athenz/zms/var/keys/zms_private.pem
03:14:25.837 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.auth.oauth.jwt.parser_factory_class, value=com.yahoo.athenz.auth.oauth.auth0.Auth0JwtParserFactory
03:14:25.837 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.zms.authority_classes, value=com.yahoo.athenz.auth.oauth.CertificateJwtAccessTokenAuthority,com.yahoo.athenz.auth.impl.
CertificateAuthority
03:14:25.838 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.auth.oauth.jwt.verify_cert_thumbprint, value=true
03:14:25.838 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.zms.jdbc_store, value=jdbc:mysql://athenz-zms-db:3306/zms_server
03:14:25.838 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.auth.oauth.jwt.claim.scope, value=openid zms/v1
03:14:25.838 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.auth.oauth.jwt.claim.aud, value=athenz/zms
03:14:25.839 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.zms.solution_templates_fname, value=/opt/athenz/zms/conf/zms_server/solution_templates.json
03:14:25.839 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.auth.private_key_store.private_key_id, value=0
03:14:25.839 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.zms.domain_admin, value=user.github-7654321
03:14:25.839 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.auth.oauth.jwt.parser.jwks_url, value=https://wzdev.auth0.com/.well-known/jwks.json
03:14:25.839 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.user_domain, value=user
03:14:25.840 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.zms.object_store_factory_class, value=com.yahoo.athenz.zms.store.impl.JDBCObjectStoreFactory
03:14:25.840 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.auth.oauth.jwt.authn_challenge_realm, value=registered_users@athenz.io
03:14:25.840 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.zms.jdbc_user, value=zms_admin
03:14:25.840 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.zms.no_auth_uri_list, value=/zms/v1/status
03:14:25.840 [main] INFO  c.y.a.c.s.util.ConfigProperties - property name=athenz.zms.authz_service_fname, value=/opt/athenz/zms/conf/zms_server/authorized_services.json
03:14:25.842 [main] INFO  com.yahoo.athenz.zms.ZMSImpl - init: using maximum domain name length: 128
03:14:25.851 [main] DEBUG com.yahoo.athenz.zms.ZMSImpl - Loading authority com.yahoo.athenz.auth.oauth.CertificateJwtAccessTokenAuthority...
03:14:25.851 [main] ERROR com.yahoo.athenz.zms.ZMSImpl - Invalid Authority class: com.yahoo.athenz.auth.oauth.CertificateJwtAccessTokenAuthority error: com.yahoo.athenz.auth.oauth.CertificateJwtAccess
TokenAuthority
03:14:25.853 [main] WARN  o.e.j.s.handler.ContextHandler.zms - unavailable
java.lang.IllegalArgumentException: Invalid authority
        at com.yahoo.athenz.zms.ZMSImpl.loadAuthorities(ZMSImpl.java:750)
        at com.yahoo.athenz.zms.ZMSImpl.<init>(ZMSImpl.java:420)
        at com.yahoo.athenz.zms.ZMSBinder.configure(ZMSBinder.java:24)
        at org.glassfish.jersey.internal.inject.AbstractBinder.invokeConfigure(AbstractBinder.java:256)
        at org.glassfish.jersey.internal.inject.AbstractBinder.getBindings(AbstractBinder.java:246)
        at org.glassfish.jersey.internal.inject.Bindings.getBindings(Bindings.java:44)
        at org.glassfish.jersey.internal.inject.AbstractBinder.lambda$getBindings$1(AbstractBinder.java:248)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.glassfish.jersey.internal.inject.AbstractBinder.getBindings(AbstractBinder.java:249)
        at org.glassfish.jersey.internal.inject.Bindings.getBindings(Bindings.java:44)
        at org.glassfish.jersey.inject.hk2.Hk2Helper.bind(Hk2Helper.java:66)
        at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.register(ImmediateHk2InjectionManager.java:58)
        at org.glassfish.jersey.model.internal.CommonConfig.configureBinders(CommonConfig.java:641)
        at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:622)
        at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:328)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
        at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
 ```

Thanks.

**Comment by WindzCUHK** [comment]
@hiyosi Oh, thank you for trying out.

Sorry that I am still working the new Authority.
Please remove the `com.yahoo.athenz.auth.oauth.CertificateJwtAccessTokenAuthority,` from the config files, it is not required if you just want to bootstrap Athenz.
https://github.com/WindzCUHK/athenz/blob/4625cdbb518f2416e0e220506a1150b904e6d1c2/docker/zms/conf/zms.properties#L12
https://github.com/WindzCUHK/athenz/blob/4625cdbb518f2416e0e220506a1150b904e6d1c2/docker/zts/conf/zts.properties#L12

**Comment by hiyosi** [comment]
In my environment (macOS), it could not be set CN/SAN value for the certificate correctly.
But after workaround it, I could run Athenz components successfully.

e.g, I guess `athenz-zms-server` is correct value for SAN of certificate. But it would be set "Not Defined".
https://github.com/WindzCUHK/athenz/blob/zms-on-external-IdP/docker/sample/zms/create-self-signed-certs.sh#L11-L24

FYI, If bulding athenz on macOS, we need to install some tools as follow.

```
$ homebrew install gnu-sed gnu-tar findutils coreutils
```

Thank you

**Comment by WindzCUHK** [comment]
@hiyosi 
Thank you for point out. I will try to include the Mac dependency somewhere in the document later on.

Sorry that the document is still WIP.
The certificate is not correct because `LibreSSL` in Mac does not support ENV.
Please refer to: https://github.com/WindzCUHK/athenz/blob/zms-on-external-IdP/docker/docs/try-out-Athenz-with-self-signed-CA.md#note-for-mac-users
