### ISSUE TITLE
Timeout properties don't work at the latest version of athenz-zms-java-client 

### ISSUE THREAD

**Issue by TakuyaMatsu** [yahoo/athenz#894]
Hello.
`ZMS_CLIENT_PROP_READ_TIMEOUT` and `ZMS_CLIENT_PROP_CONNECT_TIMEOUT` don't seem to work at latest athenz-zms-java-client.

# Problem?
I think timeout properties are overwritten by `withConfig(clientConfig)`.
https://github.com/yahoo/athenz/blob/9b2f1202663455322037390be2feb02d7ca0b854/clients/java/zms/src/main/java/com/yahoo/athenz/zms/ZMSClient.java#L381-L384

so old version is working 
https://github.com/yahoo/athenz/blob/d767dc28dcd07d1bfdd38126fb578a10fd9fead3/clients/java/zms/src/main/java/com/yahoo/athenz/zms/ZMSClient.java#L348-L350

## Fix
Change to setting properties for ClientConfig.
```
         ClientConfig clientConfig = new ClientConfig(jacksonJsonProvider)
                 .property(ClientProperties.CONNECT_TIMEOUT, connectTimeout)
                 .property(ClientProperties.READ_TIMEOUT, readTimeout);

         Client rsClient = builder
                 .withConfig(clientConfig)
                 .build();
         client = new ZMSRDLGeneratedClient(zmsUrl, rsClient);
```
OR
delete `withConfig(clientConfig)`, like old version zms-client
```
        Client rsClient = builder.property(ClientProperties.CONNECT_TIMEOUT, connectTimeout)
            .property(ClientProperties.READ_TIMEOUT, readTimeout)
            .build();
```

# Test
Test code

```
package com.hoge.test;

import com.yahoo.athenz.zms.ZMSClient;

public class ZMSClientSample {
    public static final String ZMS_CLIENT_PROP_READ_TIMEOUT    = "athenz.zms.client.read_timeout";
    public static final String ZMS_CLIENT_PROP_CONNECT_TIMEOUT = "athenz.zms.client.connect_timeout";

    public static void main(String[] args) {
        String baseUrl = args[0];
        String domainName = args[1];
        String roleName = args[2];
        String readTimeout = args[3];
        String connTimeout = args[4];

        System.setProperty(ZMS_CLIENT_PROP_READ_TIMEOUT, readTimeout);
        System.setProperty(ZMS_CLIENT_PROP_CONNECT_TIMEOUT, connTimeout);

        ZMSClient zmsClient = new ZMSClient(baseUrl);
        zmsClient.getRole(domainName, roleName, false, true);
    }
}
```

and sleep-server.js

```
#!/usr/local/bin/node
var http = require('http')

server = http.createServer()
server.on('request', function(req, res) {
  setTimeout(function() {
    res.setHeader('Content-Type', 'text/plain')
    res.writeHead(200)
    res.write('200 - OK.')
    res.end()
  }, 300 * 1000)
});

server.listen(4000, function() {
  console.log('start listening on port 4000...')
});
```

### Run with old version (1.7.36)
ZMS_CLIENT_PROP_CONNECT_TIMEOUT : 1000ms
`time` command result : **cpu 2.794 total**.  Maybe `connect timed out` is working.

```
% cat pom.xml | grep \<athenz.version\>
        <athenz.version>1.7.36</athenz.version>

% mvn clean package

% time java -jar target/athenz-zms-java-client-sample-jar-with-dependencies.jar http://blackhole.webpagetest.org hoge admin 3000 1000

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.yahoo.athenz.zms.ZMSClientException: ResourceException (400): java.net.SocketTimeoutException: connect timed out
        at com.yahoo.athenz.zms.ZMSClient.getRole(ZMSClient.java:786)
        at com.yahoo.athenz.yonakada.ZMSClientSample.main(ZMSClientSample.java:27)
java -jar target/athenz-zms-java-client-sample-jar-with-dependencies.jar  hog  1.04s user 0.12s system 41% cpu 2.794 total
```

### Run with latest version (1.8.50)
ZMS_CLIENT_PROP_CONNECT_TIMEOUT : 1000ms
`time` command result : **cpu 1:10.91 total**.  `connect timed out` is NOT working.

```
% cat pom.xml | grep \<athenz.version\>
        <athenz.version>1.8.50</athenz.version>
        
% mvn clean package

% time java -jar target/athenz-zms-java-client-sample-jar-with-dependencies.jar http://blackhole.webpagetest.org hoge admin 3000 1000

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
^C ##### (STOPPED)
java -jar target/athenz-zms-java-client-sample-jar-with-dependencies.jar  hog  2.20s user 0.21s system 3% cpu 1:10.91 total
```

### Run with old version (1.7.36)
ZMS_CLIENT_PROP_READ_TIMEOUT : 3000ms
`time` command result : **cpu 4.350 total**.  Maybe `read timed out` is working.

```
### start sleep-server.js ###
% ./sleep-server.js &

% cat pom.xml | grep \<athenz.version\>
        <athenz.version>1.7.36</athenz.version>

% mvn clean package

% time java -jar target/athenz-zms-java-client-sample-jar-with-dependencies.jar http://localhost:4000 hoge admin 3000 1000
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.yahoo.athenz.zms.ZMSClientException: ResourceException (400): java.net.SocketTimeoutException: Read timed out
        at com.yahoo.athenz.zms.ZMSClient.getRole(ZMSClient.java:786)
        at com.yahoo.athenz.yonakada.ZMSClientSample.main(ZMSClientSample.java:27)
java -jar target/athenz-zms-java-client-sample-jar-with-dependencies.jar  hog  0.97s user 0.18s system 26% cpu 4.350 total
```

### Run with latest version (1.8.50)
ZMS_CLIENT_PROP_READ_TIMEOUT : 3000ms
`time` command result : **cpu 42.462 total**. `read timed out` is NOT working.

```
### start sleep-server.js ###
% ./sleep-server.js &

% cat pom.xml | grep \<athenz.version\>
        <athenz.version>1.8.50</athenz.version>

% mvn clean package

% time java -jar target/athenz-zms-java-client-sample-jar-with-dependencies.jar http://localhost:4000 hoge admin 3000 1000
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
^C ##### (STOPPED)
java -jar target/athenz-zms-java-client-sample-jar-with-dependencies.jar  hog  1.99s user 0.20s system 5% cpu 42.462 total
```

**Comment by havetisyan** [comment]
@TakuyaMatsu can you please verify that fix from #898 addresses your issue as well. It is available in the 1.8.51 release. thanks.

**Comment by TakuyaMatsu** [comment]
@havetisyan 
Thank you for your reply.

I tried to test with the latest zms-client (v1.8.51), but timeout options did not work.

## Result
```
% ~/ghe/athenz-zms-java-client-sample
% cat pom.xml | grep \<athenz.version\>
        <athenz.version>1.8.51</athenz.version>

% mvn clean package

% time java -jar target/athenz-zms-java-client-sample-jar-with-dependencies.jar http://blackhole.webpagetest.org yby.takumats.provider users 3000 1000

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
^Cjava -jar target/athenz-zms-java-client-sample-jar-with-dependencies.jar  2.59s user 0.23s system 3% cpu 1:20.23 total
```

**Comment by TakuyaMatsu** [comment]
It worked ! #905 
Thank you.
